# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fitness_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  # Pods for Fitness_swift

  target 'Fitness_swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fitness_swiftUITests' do
    # Pods for testing
  end

end
